name: CI/CD

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Ou a versão que você estiver usando

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar os testes
      run: |
        python -m unittest discover -s tests

    - name: Build da imagem Docker
      run: |
        docker-compose -f docker-compose.yml build

    - name: Rodar Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Executar testes novamente no Docker
      run: |
        docker exec -it prefect-server python -m unittest discover -s tests

    - name: Derrubar os containers Docker
      run: |
        docker-compose -f docker-compose.yml down
